### ISSUE TITLE
[branch: dev] Terminal view "re-renders" every second and smears the view to be unreadable on Ubuntu

### ISSUE THREAD

**Issue by sfaber34** [BuidlGuidl/buidlguidl-client#13]
Sometimes the terminal view will start to "re-render" and add new blessed lines every second so that the view becomes smeared and can't be understood. If this issue occurs, it seems to start happening about 2 minutes after running the script.

I believe this is happening because errors or warnings are being printed to the terminal behind the client view and adding new lines at the bottom.

debugToFile() in helpers.js might be the issue but I am not 100 % on that.

I can recreate on Ubuntu by renaming const client to a junk name towards the top of monitor_components/statusBox.js. The "smearing" will start after a couple minutes of running index.js

**Comment by sfaber34** [comment]
![IMG_5806](https://github.com/user-attachments/assets/060ce6f6-4e98-443a-919c-40c1919e3850)

**Comment by Astronaut828** [comment]
I had this once, after restarting the terminal it was gone.

**Comment by sfaber34** [comment]
I'm pretty sure it's caused by console.error() while the client is running. I replaced console.error() with debugToFile() and I think it might be fixed. Will leave this open for a while because I'm not 100 % sure it's fixed.

**Comment by sfaber34** [comment]
Fixed
